language: ruby
rvm:
 - 2.4.3

script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec

services:
  - postgresql

notifications:
  email: false
  slack:
      on_success: always
