language: ruby
rvm:
 - 2.4.3

script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec
  
before_install:
  - bundle install --no-deployment
  - gem update bundler

services:
  - postgresql
  

notifications:
  email: false
  slack:
      on_success: always
